apiVersion: v1
kind: ConfigMap
metadata:
  name: test-vars
  namespace: e2e-agent
data:
  REST_PORT: "10012"
  MAYASTOR_PORT: "10124"
  MCP_REST_PORT: "30011"
  E2E_HOST_ADDR: ""
  ZFS: |
    #!/bin/sh
    if [ -x /host/sbin/zfs ]; then
      chroot /host /sbin/zfs "$@"
    elif [ -x /host/usr/sbin/zfs ]; then
      chroot /host /usr/sbin/zfs "$@"
    else
      chroot /host zfs "$@"
    fi
  ZPOOL: |
    #!/bin/sh
    if [ -x /host/sbin/zpool ]; then
      chroot /host /sbin/zpool "$@"
    elif [ -x /host/usr/sbin/zpool ]; then
      chroot /host /usr/sbin/zpool "$@"
    else
      chroot /host zpool "$@"
    fi
  LVM: |
    #!/bin/sh
    if [ -x /host/sbin/lvm ]; then
      chroot /host /sbin/lvm "$@"
    elif [ -x /host/usr/sbin/lvm ]; then
      chroot /host /usr/sbin/lvm "$@"
    else
      chroot /host lvm "$@"
    fi

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: e2e-rest-agent
  labels:
    app: e2e-rest-agent
  namespace: e2e-agent
spec:
  selector:
    matchLabels:
        app: e2e-rest-agent
  template:
    metadata:
      labels:
        app: e2e-rest-agent
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: e2e-rest-agent
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          envFrom:
          - configMapRef:
              name: test-vars
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          image: openebs/e2e-agent:v3.0.4
          imagePullPolicy: Always
          volumeMounts:
            - name: host-root
              mountPath: /host
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
            - name: udev
              mountPath: /run/udev
            - mountPath: /sbin/zfs
              name: chroot-zfs
              subPath: ZFS
            - mountPath: /sbin/lvm
              name: chroot-lvm
              subPath: LVM
            - mountPath: /sbin/zpool
              name: chroot-zpool
              subPath: ZPOOL
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
        - name: udev
          hostPath:
            path: /run/udev
            type: Directory
        - name: chroot-zfs
          configMap:
            defaultMode: 0555
            name: test-vars
        - name: chroot-lvm
          configMap:
            defaultMode: 0555
            name: test-vars
        - name: chroot-zpool
          configMap:
            defaultMode: 0555
            name: test-vars
          
---
