name: K8s CI
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  k8s-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          kvm: true
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell shell.nix --run "echo"
      - name: Go checks
        run: |
          nix-shell shell.nix --run "./scripts/go-checks.sh"
      - name: BootStrap k8s cluster
        run: |
          nix-shell shell.nix --run "./scripts/k8s/deployer.sh start --workers 1 --zfs --lvm" 
      - name: E2E smoke test
        run: |
          nix-shell shell.nix --run "./scripts/e2e-test.sh --testplan selfci"
      - name: Setup tmate session
        if: ${{ failure() }}
        timeout-minutes: 10
        uses: mxschmitt/action-tmate@v3

