name: K8s CI
# on:
#   pull_request:
#     types: ['opened', 'edited', 'reopened', 'synchronize']
# Since the on property is required, using the workflow_dispatch event, 
# which allows you to manually trigger the workflow from the GitHub Actions interface.
on:
  workflow_dispatch:

jobs:
  k8s-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          kvm: true
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell shell.nix --run "echo"
      - name: BootStrap k8s cluster
        run: |
          nix-shell shell.nix --run "./scripts/k8s/deployer.sh start --label --install-zfs --install-lvm"
